spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "testdb"
      username: "mongoadmin"
      password: "secret"
      authentication-database: "admin"

debug: false